server:
  servlet:
    session:
      cookie:
        name: legacy-session
        path: /
        same-site: strict
        http-only: true
        secure: false
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false
  port: 3001

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  session:
    redis:
      namespace: legacy:session
    timeout: 168h

  thymeleaf:
    prefix: classpath:/static/

  web:
    resources:
      static-locations: classpath:/static

  datasource:
    url: ENC(9AItb1GKpg5+epzH1JmuxHOgVP7TmyV8h9IEQTOuFOPsSFjR5Dthhu+ASzLIbQEc8UZrdXiSUyI4Fk+2BvwXbmvWklqyURevFy0VxWVTLRs=)
    username: ENC(vNVfcvvErIsea7uBF0I16DPZVT6XdTlwTDVvhHrfUEftjNktoEDMrltR6drEk+8J)
    password: ENC(XocV1gFO+q78pqqpLTnU7UiQY3layssp6gL+RDPyHm0ZHUUa2BzKJMlVMdimmVE1E2a+RPOhUPwPqXogpKXSOVunzdQDYInXHHVnzlhGNPs=)
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 8435
