server:
  servlet:
    session:
      cookie:
        name: legacy-session
        path: /
        same-site: strict
        http-only: true
        secure: true
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false
  port: 3001

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  session:
    redis:
      namespace: legacy:session
    timeout: 168h

  thymeleaf:
    prefix: classpath:/static/

  web:
    resources:
      static-locations: classpath:/static

  datasource:
    url: jdbc:postgresql://localhost:8473/neon
    username: neon
    password: zKvHLM5WqoDuWWL5Uu984pIz9ytRStZq
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 8435
